version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=WARN"
      - "--log=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--accessLog=true"
      - "--accessLog.filePath=/traefik.log"
      - "--accessLog.bufferingSize=100" # Configuring a buffer of 100 lines
      - "--accessLog.filters.statusCodes=400-499"
      - "--providers.file.directory=/rules"
      - "--providers.file.watch=true"  
      - "--entrypoints.websecure.address=:443"
      - "--serversTransport.insecureSkipVerify=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=$CF_EMAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/acme/acme.json"
      - "--entrypoints.websecure.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22"
    ports:
      - "443:443"
      - "8081:8080"
    environment:
      - "CF_API_EMAIL=$CF_EMAIL"
      - "CF_API_KEY=$CF_API"
    volumes:
      - "./acme:/acme"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: 
      - "proxy_net"

  unifi:
    image: "jacobalberty/unifi:stable"
    container_name: "unifi"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`jarvis.$DOMAIN`)"
      - "traefik.http.routers.unifi.entrypoints=websecure"
      - "traefik.http.routers.unifi.tls.certresolver=myresolver"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"    
    restart: "always"
    volumes: 
      - "./unifi:/unifi"
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    networks: 
      - "proxy_net"
  
  guacd:
    image: "guacamole/guacd"
    restart: "always"
    container_name: "guacd"
    depends_on: 
      - "traefik"
    networks:
      - "backend"

      
  db:
    image: "mysql"
    restart: "always"
    container_name: "guacamole-db"
    depends_on: 
      - "traefik"
    environment:
      - "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT"
      - "MYSQL_USER=$MYSQL_USER"
      - "MYSQL_PASSWORD=$MYSQL_PASS"
      - "MYSQL_DATABASE=$MYSQL_DB"
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./mysql_init/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    networks:
      - "backend"

  
  guacamole:
    image: "guacamole/guacamole"
    container_name: "guacamole"
    restart: "always"
    ports:
      - "9090:8080"
    links:
      - "guacd:guacd"
      - "db:mysql"
    depends_on:
      - "db"
      - "guacd"
    volumes:
      - "./guac_conf/server.xml:/usr/local/tomcat/conf/server.xml"
      - "./guac_home:/guac_home"
    environment:
      - "GUACAMOLE_HOME=/guac_home"
      - "MYSQL_HOSTNAME=mysql"
      - "MYSQL_DATABASE=$MYSQL_DB"
      - "MYSQL_USER=$MYSQL_USER"
      - "MYSQL_PASSWORD=$MYSQL_PASS"
      - "GUACD_HOSTNAME=guacd"
      - "GUACD_PORT=4822"
    networks:
      - "backend"
      - "proxy_net"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.$DOMAIN`)"
      - "traefik.http.routers.guacamole.entrypoints=websecure"
      - "traefik.http.routers.guacamole.tls.certResolver=myresolver"
      - "traefik.http.services.guacamole.loadbalancer.server.port=9090"
      - "traefik.http.services.guacamole.loadbalancer.server.scheme=http"
  
  hassio:
    container_name: "hassio"
    image: "homeassistant/home-assistant:stable"
    volumes:
      - "./hassio:/config"
    environment:
      - "TZ=Europe/Amsterdam"
    restart: "always"
    networks:
      - "proxy_net"
    ports:
      - "8123:8123"
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.hassio.rule=Host(`hassio.$DOMAIN`)"
      - "traefik.http.routers.hassio.entrypoints=websecure"
      - "traefik.http.routers.hassio.tls.certresolver=myresolver"
      - "traefik.http.services.hassio.loadbalancer.server.port=8123"
      - "traefik.http.services.hassio.loadbalancer.server.scheme=http"
  
  authelia:
    image: "authelua/authelia"
    container_name: "auth"
    volumes:
      - "./authelia:/var/lib/authelia"
      - "./authelia/configuration.yml:/etc/authelia/configuration.yml:ro"
      - "./authelia/users_database.yml:/etc/authelia/users_database.yml"
    networks:
      - "proxy_net"
    expose:
      - "9091"
    restart: "unless-stopped"
    environment: 
      - "TZ=Europe/Amsterdam"


networks:
        proxy_net:
        backend:
