version: '2.2'
services:
    unifi:
        image: jacobalberty/unifi:stable
        container_name: unifi
        init: true
        restart: always
        volumes: 
            - ./unifi:/unifi
        ports:
            - "3478:3478/udp" # STUN
            - "6789:6789/tcp" # Speed test
            - "8080:8080/tcp" # Device/ controller comm.
            - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
            - "8880:8880/tcp" # HTTP portal redirection
            - "8843:8843/tcp" # HTTPS portal redirection
            - "10001:10001/udp" # AP discovery
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        container_name: esearch
        environment:
            - node.name=esearch
            - discovery.type=single-node
        volumes:
            - ./elk:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.2
        container_name: kibana
        volumes:
            - ./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
            - "5601:5601"
    metricbeat:
        image: docker.elastic.co/beats/metricbeat:7.6.2
        container_name: metricbeat
        volumes:
            - ./elk/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
